import { defineConfig } from "vitest/config";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  test: {
    environment: "jsdom",
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html", "lcov"],
      include: ["src/**/*.{js,jsx,ts,tsx}"],
      thresholds: {
        statements: 70,
        branches: 50,
        functions: 70,
        lines: 70,
      },
      exclude: [
        "node_modules/**",
        "dist/**",
        "coverage/**",
        "**/*.config.{js,ts}",
        "**/*.d.ts",
        "**/__tests__/**",
        "**/types.js",
        "src/main.jsx",
        "src/components/ui/**",
        "src/components/landing/**",
        "src/pages/auth/**",
        "src/pages/profile/**",
        "src/pages/leaderboard/**",
        "src/pages/landing/**",
        "src/layouts/**",
        "src/components/Navbar.jsx",
        "src/components/AnimatedSection.jsx",
        "src/components/ParallaxSection.jsx",
        "src/components/GuestRoute.jsx",
        "src/components/ProtectedRoute.jsx",
        "src/components/ErrorBoundary.jsx",
        "src/components/LoadingPage.jsx",
        "src/components/UserMenu.jsx",
        "src/components/ThemeSwitcher.jsx",
        "src/components/BottomDock.jsx",
        "src/components/FloatingMenu.jsx",
        "src/components/KeyboardShortcuts.jsx",
        "src/components/CommandPalette.jsx",
        "src/components/AuthLayout.jsx",
        "src/services/socketService.js",
        "src/services/multiplayerGameService.js",
        "src/utils/tetrisAgent.js",
        "src/routes/**",
        "src/hooks/useSocket.jsx",
        "src/hooks/useMultiplayerGameService.jsx",
        "src/hooks/useAuthMutations.js",
        "src/hooks/useAuthQuery.js",
        "src/constants/modes.js",
        "src/data/**",
        "src/pages/game/index.jsx",
        "src/pages/game/GameModeSelection.jsx",
        "src/pages/game/MultiplayerLobby.jsx",
        "src/pages/game/GamePlay.jsx",
        "src/pages/game/MultiplayerGameRoom.jsx",
        "src/api/index.js",
        "src/api/auth/index.js",
        "src/api/game/index.js",
        "src/api/auth/useAuthMutations.js",
        "src/components/game/Matchmaking.jsx",
        "src/components/game/RoomDialog.jsx",
        "src/components/game/OpponentBoard.jsx",
        "src/components/game/BoardGlass.jsx",
        "src/components/game/GameDialogs.jsx",
        "src/components/game/GameStats.jsx",
        "src/components/profile/**",
      ],
    },
  },
});
