services:
  db:
    image: postgres:17.0
    hostname: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}
      - FORTY_TWO_CLIENT_ID=${FORTY_TWO_CLIENT_ID}
      - FORTY_TWO_CLIENT_SECRET=${FORTY_TWO_CLIENT_SECRET}
      - FORTY_TWO_CALLBACK_URL=${FORTY_TWO_CALLBACK_URL}
    ports:
      - "3000:3000"
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: /api
    environment:
      - VITE_API_BASE=/api
    ports:
      - "5173:80"
    depends_on:
      - server


volumes:
  pgdata:
