services:
  db:
    image: postgres:17.0
    hostname: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}
      - FORTY_TWO_CLIENT_ID=${FORTY_TWO_CLIENT_ID:-}
      - FORTY_TWO_CLIENT_SECRET=${FORTY_TWO_CLIENT_SECRET:-}
      - FORTY_TWO_CALLBACK_URL=${FORTY_TWO_CALLBACK_URL:-}
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  drizzle-studio:
    container_name: red-tetris-drizzle-studio-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    expose:
      - 8899/tcp
    ports:
      - "127.0.0.1:8899:8899/tcp"
    volumes:
      - ./server:/app
      - drizzle-node_modules:/app/node_modules/
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    restart: always
    depends_on:
      - db
    command: sh -c "npm install && exec npx drizzle-kit studio --host 0.0.0.0 --port 8899"

volumes:
  pgdata:
  drizzle-node_modules:
